<a href="https://colab.research.google.com/github/AIsavvyAyeshafathima/VARIATION-OF-GPT-MODEL/blob/main/gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🚀 GPT

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In this notebook, we'll walk through the steps required to train your own GPT model on the wine review dataset

The code is adapted from the excellent [GPT tutorial](https://keras.io/examples/generative/text_generation_with_miniature_gpt/) created by Apoorv Nandan available on the Keras website.

In [2]:
%load_ext autoreload
%autoreload 2
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

## 0. Parameters <a name="parameters"></a>

In [3]:
VOCAB_SIZE = 10000
MAX_LEN = 80
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. Load the data <a name="load"></a>

In [4]:
# Load the full dataset
with open("/content/drive/MyDrive/winemag-data-130k-v2.json") as json_data:
    wine_data = json.load(json_data)

In [5]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [6]:
# Filter the dataset
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [7]:
# Count the recipes
n_wines = len(filtered_data)
print(f"{n_wines} recipes loaded")

129907 recipes loaded


In [8]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.


## 2. Tokenize the data <a name="tokenize"></a>

In [9]:
# Pad the punctuation, to treat them as separate 'words'
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [10]:
# Display an example of a recipe
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [11]:
# Convert to a Tensorflow Dataset
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

In [12]:
# Create a vectorisation layer
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [13]:
# Adapt the layer to the training set
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [14]:
# Display some token:word mappings
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [15]:
# Display the same example converted to ints
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. Create the Training Set <a name="create"></a>

In [16]:
# Create the training set of recipes and the same text shifted by one word
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [17]:
example_input_output = train_ds.take(1).get_single_element()

In [18]:
# Example Input
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,  280,  536,    2, 1185,    2,   53,   27,    2,
          8,  242, 1056,    9,  729,   18,   21, 7087,    3,  617,   16,
          5,    6,  155,  816,    9,   44,  101,    4,   52, 1683,    3,
       5647,    7,   11,    8,  555,   14,   19,  840,   46,  893, 1324,
          4,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

In [19]:
# Example Output (shifted by one token)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,  280,  536,    2, 1185,    2,   53,   27,    2,    8,
        242, 1056,    9,  729,   18,   21, 7087,    3,  617,   16,    5,
          6,  155,  816,    9,   44,  101,    4,   52, 1683,    3, 5647,
          7,   11,    8,  555,   14,   19,  840,   46,  893, 1324,    4,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

## 5. Create the causal attention mask function <a name="causal"></a>

In [20]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

## 6. Create a Transformer Block layer <a name="transformer"></a>

In [21]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. Create the Token and Position Embedding <a name="embedder"></a>

In [22]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. Build the Transformer model <a name="transformer_decoder"></a>

In [23]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [24]:
gpt.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, None)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ token_and_position_embedding         │ (None, None, 256)           │       2,580,480 │
│ (TokenAndPositionEmbedding)          │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ transformer_block (TransformerBlock) │ [(None, None, 256), (None,  │         658,688 │
│                                      │ 2, None, None)]             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, None, 10000)         │       2,570,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,809,168 (22.16 MB)

 Trainable params: 5,809,168 (22.16 MB)

 Non-trainable params: 0 (0.00 B)

In [25]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("./models/gpt", compile=True)

## 9. Train the Transformer <a name="train"></a>

In [26]:
# Create a TextGenerator checkpoint
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\ngenerated text:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [28]:
# Create a model save checkpoint
model_checkpoint_callback = callbacks.ModelCheckpoint(
    filepath="./checkpoint/checkpoint.weights.h5",
    save_weights_only=True,
    save_freq="epoch",
    verbose=0,
)

tensorboard_callback = callbacks.TensorBoard(log_dir="./logs")

# Tokenize starting prompt
text_generator = TextGenerator(vocab)

In [29]:
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[model_checkpoint_callback, tensorboard_callback, text_generator],
)

Epoch 1/5
4059/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.5889
generated text:
wine review : italy : piedmont : barbera : this is a compact barbera with a firmly tannic close with a crisp , elegant consistency and dense density . 

4060/4060 ━━━━━━━━━━━━━━━━━━━━ 120s 27ms/step - loss: 2.5887
Epoch 2/5
4058/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1.9763
generated text:
wine review : chile : maule valley : syrah : dry oak aromas include hints of raw wood grain and milk chocolate . this rustic carignan is sticky and hard on the palate . savory flavors of oak end things benefit from clarity as much as if the raspberries , black fruits on the finish . 

4060/4060 ━━━━━━━━━━━━━━━━━━━━ 109s 27ms/step - loss: 1.9763
Epoch 3/5
4058/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1.8919
generated text:
wine review : us : washington : gewürztraminer : the stone fruit and flowers inform the entry of this variety coming from a vineyard . light , floral jasmine notes emerge even though i

In [31]:
# Save the final model
gpt.save("./models/gpt.h5")

# 3. Generate text using the Transformer

In [32]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

In [33]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=1.0
)


generated text:
wine review : us : california : zinfandel : soft and buttery , this tastes young and fruity in blackberry and cherry sauce , with thin , sweet flavors of pear and raisins . a nice mix of acidity . 



In [34]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.5
)


generated text:
wine review : italy : veneto : glera : this opens with aromas of acacia , acacia , toasted nut , ripe yellow apple and a whiff of honey . the creamy palate offers dried apricot , candied nectarine zest , lemon zest and a hint of bitter almond alongside brisk acidity . 



In [35]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


generated text:
wine review : germany : mosel : riesling : a touch of smoke and spice lend a fresh , mineral tone to this dry , honeyed , sunny tangerine and peach flavors . it ' s a straightforward quaffer , showing a bit of spritz on the finish . 



::   	100.0%
-:   	0.0%
grosso:   	0.0%
[UNK]:   	0.0%
blanc:   	0.0%
--------



mosel:   	85.42%
rheingau:   	6.46%
rheinhessen:   	3.11%
pfalz:   	2.38%
franken:   	1.99%
--------



::   	98.89%
-:   	1.11%
grosso:   	0.0%
[UNK]:   	0.0%
oil:   	0.0%
--------



riesling:   	99.98%
pinot:   	0.01%
white:   	0.0%
sparkling:   	0.0%
rosé:   	0.0%
--------



::   	100.0%
-:   	0.0%
grosso:   	0.0%
blanc:   	0.0%
du:   	0.0%
--------



while:   	33.45%
a:   	27.42%
whiffs:   	9.16%
this:   	5.9%
[UNK]:   	2.19%
--------



bit:   	37.82%
whiff:   	17.2%
hint:   	14.55%
touch:   	11.37%
[UNK]:   	1.48%
--------



of:   	99.87%
blossomy:   	0.04%
off:   	0.04%
sweet:   	0.03%
weightier:   	0.0%
--------



smoke:   	46.9%
petrol:   	19.43%
struck:   	12.4%
sweet:   	3.12%
sweetness:   	2.94%
--------



lends:   	46.19%
and:   	45.6%
mingles:   	2.93%
,:   	1.96%
leads:   	0.87%
--------



spice:   	16.96%
crushed:   	12.67%
slate:   	12.52%
smoke:   	11.07%
mineral:   	9.08%
--------



lend:   	57.52%
accent:   	13.5%
aromas:   	6.03%
on:   	3.24%
meld:   	3.08%
--------



a:   	93.2%
an:   	2.15%
warmth:   	1.84%
complexity:   	1.68%
savory:   	0.27%
--------



savory:   	85.88%
fresh:   	7.64%
mineral:   	0.98%
crisp:   	0.62%
floral:   	0.51%
--------



,:   	74.35%
tone:   	10.82%
apple:   	7.42%
character:   	2.82%
floral:   	1.44%
--------



mineral:   	40.18%
savory:   	8.9%
blossomy:   	7.46%
floral:   	5.43%
herbaceous:   	3.72%
--------



tone:   	99.71%
-:   	0.15%
character:   	0.07%
vibe:   	0.01%
edge:   	0.01%
--------



to:   	99.99%
in:   	0.0%
on:   	0.0%
and:   	0.0%
for:   	0.0%
--------



this:   	99.06%
the:   	0.43%
fresh:   	0.14%
pristine:   	0.11%
bright:   	0.08%
--------



dry:   	55.27%
spry:   	8.7%
off:   	6.15%
crisp:   	5.4%
zesty:   	4.13%
--------



,:   	85.71%
riesling:   	12.01%
-:   	1.06%
off:   	0.51%
wine:   	0.48%
--------



crisp:   	35.8%
spry:   	13.6%
steely:   	10.88%
full:   	9.07%
medium:   	8.75%
--------



,:   	42.75%
riesling:   	38.3%
wine:   	10.72%
white:   	3.97%
-:   	2.37%
--------



full:   	38.14%
medium:   	13.97%
crisp:   	4.84%
honeyed:   	4.48%
almost:   	2.8%
--------



tangerine:   	69.53%
white:   	11.81%
peach:   	5.13%
,:   	3.03%
yellow:   	2.9%
--------



and:   	99.81%
,:   	0.15%
-:   	0.02%
acidity:   	0.01%
flavors:   	0.0%
--------



tangerine:   	39.72%
lemon:   	21.86%
peach:   	16.58%
yellow:   	9.93%
grapefruit:   	3.9%
--------



flavors:   	99.59%
notes:   	0.27%
-:   	0.08%
on:   	0.02%
.:   	0.01%
--------



.:   	86.75%
on:   	10.29%
in:   	2.16%
that:   	0.39%
,:   	0.22%
--------



it:   	85.25%
the:   	12.77%
crisp:   	0.49%
brisk:   	0.22%
zesty:   	0.19%
--------



':   	99.89%
finishes:   	0.09%
is:   	0.01%
penetrates:   	0.0%
has:   	0.0%
--------



s:   	100.0%
ll:   	0.0%
d:   	0.0%
09:   	0.0%
[UNK]:   	0.0%
--------



a:   	43.04%
full:   	17.51%
delicately:   	3.87%
light:   	2.68%
crisp:   	2.48%
--------



straightforward:   	36.64%
bit:   	14.56%
refreshingly:   	14.44%
refreshing:   	3.6%
spry:   	2.54%
--------



quaffer:   	62.41%
yet:   	16.75%
,:   	16.29%
but:   	2.73%
wine:   	1.52%
--------



,:   	60.7%
with:   	11.21%
.:   	10.5%
that:   	8.91%
to:   	2.72%
--------



but:   	90.21%
yet:   	6.98%
with:   	1.67%
finishing:   	0.56%
and:   	0.25%
--------



a:   	98.88%
some:   	0.7%
an:   	0.14%
good:   	0.05%
surprising:   	0.03%
--------



hint:   	55.33%
bit:   	15.99%
kiss:   	9.22%
touch:   	4.92%
moderately:   	2.6%
--------



of:   	97.73%
more:   	1.66%
on:   	0.59%
off:   	0.01%
like:   	0.0%
--------



a:   	29.71%
sweetness:   	13.35%
spritz:   	10.4%
maturity:   	8.16%
astringency:   	6.65%
--------



on:   	76.74%
and:   	19.46%
.:   	2.04%
,:   	1.25%
that:   	0.22%
--------



the:   	100.0%
this:   	0.0%
a:   	0.0%
its:   	0.0%
it:   	0.0%
--------



palate:   	81.33%
finish:   	16.47%
midpalate:   	1.71%
nose:   	0.39%
tongue:   	0.05%
--------



.:   	99.84%
,:   	0.15%
and:   	0.01%
with:   	0.0%
but:   	0.0%
--------



:   	99.33%
drink:   	0.66%
it:   	0.0%
enjoy:   	0.0%
try:   	0.0%
--------



In [36]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.2
)


generated text:
wine review : italy : tuscany : sangiovese : this opens with aromas of red berry , underbrush , grilled herb and a whiff of menthol . the straightforward palate offers dried black cherry , licorice and a hint of clove alongside bracing tannins . drink through 2017 . 

